In [1]:
import os
import cv2 as cv
import numpy as np
from tqdm import tqdm
from tensorflow.keras.preprocessing.image import img_to_array,array_to_img,load_img

In [2]:
data_path = os.path.join(os.curdir,'dataset')
classes = ['without_band', 'with_band']

### Loading all the images

In [3]:
# height * width * channel
all_images = []
for cls in classes:
    cls_path = os.path.join(data_path,cls)
    class_images = []
    for img_d in os.listdir(cls_path):
        img_path = os.path.join(cls_path,img_d)
        print(img_path)
        sub_images = []
        for img in os.listdir(img_path):
            image = os.path.join(img_path,img) #file location
#             img = load_img(image,target_size=(80,70))
            img = cv.imread(image)
            img = cv.resize(img,(80,70))
            img = img_to_array(img)
            img = img/255
            sub_images.append(img)
        class_images.append(sub_images)
    all_images.append(class_images)

.\dataset\without_band\1
.\dataset\without_band\2
.\dataset\without_band\3
.\dataset\without_band\4
.\dataset\with_band\1
.\dataset\with_band\2
.\dataset\with_band\3


In [4]:
def sample(class_data,size,label):
    sampled = []
    for i,data in enumerate(class_data):
        data = np.array(data)
        length = data.shape[0]
        idx = np.random.randint(0,length,size[i])
        sampled.append(data[idx])
    data = np.concatenate(sampled,dtype='float32')
    labels = np.array([label] * len(data),dtype='int8')
    return data,labels
# _d = sample(all_images[1],[100,200,300],1)

In [8]:
def load_data(class_data,label):
    sampled = []
    for data in class_data:
        data = np.array(data)
        sampled.append(data)
    data = np.concatenate(sampled,dtype='float32')
    labels = np.array([label] * len(data),dtype='int8')
    return data,labels

In [9]:
# negatives,n_label = sample(all_images[0],[1300,1234,1234,1234],0)
# positives,p_label = sample(all_images[1],[2000,1500,1500],1)

negatives,n_label = load_data(all_images[0],0)
positives,p_label = load_data(all_images[1],1)

In [11]:
size = positives.shape[0]
length = negatives.shape[0]
idx = np.random.randint(0,length,size)
negatives = negatives[idx]
n_label = n_label[:size]

In [3]:
# x = np.concatenate([negatives,positives])
# y = np.concatenate([n_label,p_label])
x = np.load('data_arrays/x.npy')
y = np.load('data_arrays/y.npy')

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_val,y_train,y_val = train_test_split(x,y,test_size=.2,random_state=17,
                                               shuffle=True,stratify=y)

### visualizing training images

In [18]:
ps = (x_train[y_train==1])
ns = (x_train[y_train==0])

In [19]:
print(ps.shape,ns.shape)

(18325, 70, 80, 3) (18326, 70, 80, 3)


In [20]:
for img in ns:
    cv.imshow('image',img)
    if cv.waitKey(1)&0xff == ord('q'):
        break
cv.destroyAllWindows()

In [15]:
cv.destroyAllWindows()

### Model Building

In [15]:
from tensorflow import keras

In [18]:
model = keras.models.Sequential([
    keras.layers.Conv2D(64,12,strides=2,activation='relu',padding='same',input_shape=[70,80,3]),
    keras.layers.Conv2D(128,6,strides=2,activation='relu',padding='same'),
    keras.layers.Conv2D(128,3,strides=2,activation='relu',padding='same'),
    keras.layers.Flatten(),
    keras.layers.Dense(64,activation='relu'),
    keras.layers.Dense(2,activation='softmax')
])
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',metrics=['accuracy'])
H = model.fit(x_train,y_train,batch_size=32,
              validation_data=(x_val,y_val),epochs=1)

1146/1146 [==============================] - 511s 446ms/step - loss: 0.1087 - accuracy: 0.9494 - val_loss: 0.0063 - val_accuracy: 0.9977


In [19]:
model.save('models/resistance_band_detector2.h5')

In [20]:
np.save('data_arrays/x.npy',x)
np.save('data_arrays/y.npy',y)

### Testing 

In [24]:
def show(image):
    cv.imshow('image',image)
    cv.waitKey(0)
    cv.destroyAllWindows()

In [33]:
from tensorflow import keras

In [34]:
 model = keras.models.load_model('models/resistance_band_detector2.h5')

In [ ]:
def preprocess(image):
    image = cv.resize(img,(80,70))
    image = image/255
    return image #[np.newaxis,...]

In [40]:
testing_images = os.listdir('dataset/without_band/1')
for img in testing_images:
    img = cv.imread('dataset/without_band/1/'+img)
    img = preprocess(img)
    cv.imshow('image',img)
    pred = model.predict(img[np.newaxis,...])
    pred = np.argmax(pred[0])
    if pred == 0:
        label = 'no band'
    elif pred == 1:
        label = 'yes band'
    print(label)
    if cv.waitKey(1)&0xff == ord('q'):
        break
cv.destroyAllWindows()

no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band
no band


In [31]:
cv.destroyAllWindows()

In [53]:
i = cv.imread('dataset/with_band/1/2662.jpg')
show(i)
i = preprocess(i)
model.predict(i)

array([[0.3690998, 0.6309002]], dtype=float32)

In [50]:
show(x_val[0])

In [51]:
model.predict(x_val[0].reshape(1,70,80,3))

array([[5.894997e-17, 1.000000e+00]], dtype=float32)

In [56]:
pred = model.predict(x_val)
pred = np.argmax(pred,axis=1)

In [58]:
from sklearn.metrics import confusion_matrix

In [66]:
confusion_matrix(y_val,pred)

array([[4572,    9],
       [  12, 4570]], dtype=int64)